import RefreshWrapper from "@/common/refresh-wrapper";
import NavBar from "@/components/common/nav-bar";
import { AuthProvider } from "@/context/auth-provider";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {/* <AuthProvider> */}
      <RefreshWrapper>
        <nav className="w-full h-16 sticky top-0 left-0 z-50 backdrop-blur-md bg-white/30 border-b px-6">
          <NavBar />
        </nav>
        {children}
      </RefreshWrapper>
      {/* </AuthProvider> */}
    </div>
  );
}
